#############################################################################
# Makefile for building: UAS_GS_Client
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  UAS_GS_Client.pro
# Template: app
# Command: /home/tyler/Qt/5.8/gcc_64/bin/qmake -o Makefile UAS_GS_Client.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_QUICKCONTROLS2_LIB -DQT_LOCATION_LIB -DQT_QUICK_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -D_REENTRANT
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../OpenCV/modules/core/include -I../../../OpenCV/modules/highgui/include -I../../../OpenCV/modules/objdetect/include -I../../../OpenCV/modules/imgproc/include -I../../../Qt/5.8/gcc_64/include -I../../../Qt/5.8/gcc_64/include/QtQuickControls2 -I../../../Qt/5.8/gcc_64/include/QtLocation -I../../../Qt/5.8/gcc_64/include/QtQuick -I../../../Qt/5.8/gcc_64/include/QtMultimedia -I../../../Qt/5.8/gcc_64/include/QtGui -I../../../Qt/5.8/gcc_64/include/QtQml -I../../../Qt/5.8/gcc_64/include/QtNetwork -I../../../Qt/5.8/gcc_64/include/QtPositioning -I../../../Qt/5.8/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -isystem /usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I../../../Qt/5.8/gcc_64/mkspecs/linux-g++
QMAKE         = /home/tyler/Qt/5.8/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = UAS_GS_Client1.0.0
DISTDIR = /home/tyler/NEW_UAV/UAS/front/.tmp/UAS_GS_Client1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/tyler/Qt/5.8/gcc_64/lib -Wl,-rpath-link,/home/tyler/Qt/5.8/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/tyler/OpenCV/build/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -lopencv_videoio -lopencv_objdetect -L/home/tyler/Qt/5.8/gcc_64/lib -lQt5QuickControls2 -lQt5Location -lQt5Quick -lQt5Multimedia -lQt5Gui -lQt5Qml -lQt5Network -lQt5Positioning -lQt5Core -lGL -lpthread -lpulse-mainloop-glib -lpulse -lglib-2.0 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		cvcontroller.cpp qrc_qml.cpp \
		qrc_mapviewer.cpp \
		moc_cvcontroller.cpp
OBJECTS       = main.o \
		cvcontroller.o \
		qrc_qml.o \
		qrc_mapviewer.o \
		moc_cvcontroller.o
DIST          = android/AndroidManifest.xml \
		android/gradle/wrapper/gradle-wrapper.jar \
		android/gradlew \
		android/res/values/libs.xml \
		android/build.gradle \
		android/gradle/wrapper/gradle-wrapper.properties \
		android/gradlew.bat \
		../../../Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		UAS_GS_Client.pro cvcontroller.h main.cpp \
		cvcontroller.cpp
QMAKE_TARGET  = UAS_GS_Client
DESTDIR       = 
TARGET        = UAS_GS_Client


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: UAS_GS_Client.pro ../../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.8/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.8/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.8/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.8/gcc_64/mkspecs/features/lex.prf \
		UAS_GS_Client.pro \
		qml.qrc \
		mapviewer.qrc \
		../../../Qt/5.8/gcc_64/lib/libQt5QuickControls2.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Location.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Quick.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Multimedia.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Gui.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Qml.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Network.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Positioning.prl \
		../../../Qt/5.8/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile UAS_GS_Client.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../../Qt/5.8/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.8/gcc_64/mkspecs/common/unix.conf:
../../../Qt/5.8/gcc_64/mkspecs/common/linux.conf:
../../../Qt/5.8/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt/5.8/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.8/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.8/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/5.8/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/5.8/gcc_64/mkspecs/qconfig.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.8/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.8/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/5.8/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.8/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.8/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/toolchain.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/qml_debug.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/qt.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/resources.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/moc.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/file_copies.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/5.8/gcc_64/mkspecs/features/lex.prf:
UAS_GS_Client.pro:
qml.qrc:
mapviewer.qrc:
../../../Qt/5.8/gcc_64/lib/libQt5QuickControls2.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Location.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Quick.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Multimedia.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Gui.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Qml.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Network.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Positioning.prl:
../../../Qt/5.8/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile UAS_GS_Client.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc mapviewer.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents cvcontroller.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp cvcontroller.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp qrc_mapviewer.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp qrc_mapviewer.cpp
qrc_qml.cpp: qml.qrc \
		../../../Qt/5.8/gcc_64/bin/rcc \
		SensorGaugeView.qml \
		CommandPage.qml \
		SensorGraphView.qml \
		SensorView.qml \
		SensorVerticalGaugeView.qml \
		qtquickcontrols2.conf \
		DroneViewPage.qml \
		main.qml \
		GroundSystemLayout.qml \
		png/stethoscope.png \
		png/circular-shape-silhouette.png \
		png/light-bulb.png \
		png/flag-black-shape.png \
		png/link-symbol.png \
		png/volume-up-interface-symbol.png \
		png/play-sign.png \
		png/paper-bill.png \
		png/hand-pointing-upward.png \
		png/fire-symbol.png \
		png/branch-with-leaves-black-shape.png \
		png/weibo-website-logo.png \
		png/leter-a-inside-a-black-circle.png \
		png/zoom-out.png \
		png/dashboard.png \
		png/sort-arrows-couple-pointing-up-and-down.png \
		png/share-option.png \
		png/asterisk.png \
		png/information-symbol.png \
		png/smile.png \
		png/x2-symbol-of-a-letter-and-a-number-subscript.png \
		png/meh-face-emoticon.png \
		png/italicize-text.png \
		png/open-folder.png \
		png/coffee-cup-on-a-plate-black-silhouettes.png \
		png/female-silhouette.png \
		png/envelope-of-white-paper.png \
		png/sort-down.png \
		png/compass-circular-variant.png \
		png/double-left-chevron.png \
		png/indent-right.png \
		png/cursor.png \
		png/renren-social-network-of-china-logotype.png \
		png/three-small-square-shapes.png \
		png/bar-graph-on-a-rectangle.png \
		png/arrow-pointing-to-right.png \
		png/bitbucket-logotype-camera-lens-in-perspective.png \
		png/plus-sign-in-a-black-circle.png \
		png/lemon.png \
		png/zoom-in.png \
		png/ambulance.png \
		png/adjust-contrast.png \
		png/arrow-pointing-to-left.png \
		png/html-5-logo.png \
		png/step-forward.png \
		png/thumb-down.png \
		png/facebook-logo.png \
		png/sign-in.png \
		png/horizontal-resize-option.png \
		png/open-padlock-silhouette.png \
		png/sign-out-option.png \
		png/text-file-1.png \
		png/arrowhead-pointing-up-inside-a-square-box-outline.png \
		png/facetime-button.png \
		png/bell-musical-tool.png \
		png/retweet-arrows-symbol.png \
		png/bug.png \
		png/plus-symbol-in-a-rounded-black-square.png \
		png/check.png \
		png/chevron-sign-to-right.png \
		png/arrow-down-on-black-circular-background.png \
		png/circle-shape-outline.png \
		png/beaker.png \
		png/cog-wheel-silhouette.png \
		png/underline-text-option.png \
		png/small-rocket-ship-silhouette.png \
		png/euro-currency-symbol.png \
		png/angle-arrow-down.png \
		png/font-selection-editor.png \
		png/nine-black-tiles.png \
		png/microphone-black-shape.png \
		png/caret-arrow-up.png \
		png/remove-button.png \
		png/finger-of-a-hand-pointing-to-right-direction.png \
		png/list-on-window.png \
		png/chevron-sign-down.png \
		png/sort-by-numeric-order.png \
		png/sort-by-attributes-interface-button-option.png \
		png/vimeo-square-logo.png \
		png/fast-forward-arrows.png \
		png/xing-logo.png \
		png/thumbs-up.png \
		png/shopping-cart-black-shape.png \
		png/speech-bubbles-comment-option.png \
		png/left-arrow.png \
		png/plane.png \
		png/checkered-raised-flag.png \
		png/list.png \
		png/paper-push-pin.png \
		png/download-symbol.png \
		png/edit-interface-sign.png \
		png/minus-sign-inside-a-black-circle.png \
		png/legal-hammer.png \
		png/play-button.png \
		png/undo-arrow.png \
		png/css-3-logo.png \
		png/dot-and-circle.png \
		png/turkish-lire-symbol.png \
		png/chevron-arrow-down.png \
		png/photo-camera.png \
		png/trophy.png \
		png/bookmark-white.png \
		png/reply.png \
		png/road-perspective.png \
		png/play-circle.png \
		png/power-button-off.png \
		png/camera-retro.png \
		png/step-backward.png \
		png/letter-p-symbol.png \
		png/right-chevron.png \
		png/printing-tool.png \
		png/arrow-pointing-down.png \
		png/github-character.png \
		png/four-black-squares.png \
		png/vertical-resizing-option.png \
		png/correct-symbol.png \
		png/remove-symbol.png \
		png/right-arrow-in-a-circle.png \
		png/vk-social-network-logo.png \
		png/paste-from-clipboard.png \
		png/tags.png \
		png/desktop-monitor.png \
		png/sort-by-alphabet.png \
		png/refresh-arrow.png \
		png/code.png \
		png/star.png \
		png/great-britain-pound.png \
		png/arrowheads-pointing-to-the-left.png \
		png/unlink-symbol.png \
		png/warning-sign-on-a-triangular-background.png \
		png/youtube-logo.png \
		png/telephone-symbol-button.png \
		png/moon-phase-outline.png \
		png/windows-logo-silhouette.png \
		png/signal-bars.png \
		png/folder-closed-black-shape.png \
		png/home.png \
		png/sort-reverse-alphabetical-order.png \
		png/move-option.png \
		png/trello-website-logo.png \
		png/couple-of-arrows-changing-places.png \
		png/calendar-page-empty.png \
		png/forward-button.png \
		png/question-mark-on-a-circular-black-background.png \
		png/google-plus-symbol-1.png \
		png/rounded-black-square-shape.png \
		png/vertical-ellipsis.png \
		png/video-play-square-button.png \
		png/hotel-letter-h-sign-inside-a-black-rounded-square.png \
		png/dollar-symbol.png \
		png/heart-shape-silhouette.png \
		png/fire-extinguisher.png \
		png/trash.png \
		png/chevron-arrow-up.png \
		png/open-wrench-tool-silhouette.png \
		png/upload-button.png \
		png/sort-by-attributes.png \
		png/stack-exchange-logo.png \
		png/right-quotation-mark.png \
		png/rupee-indian.png \
		png/open-folder-outline.png \
		png/spinner-of-dots.png \
		png/pause-symbol.png \
		png/facebook-logo-1.png \
		png/hand-finger-pointing-down.png \
		png/beer-jar-black-silhouette.png \
		png/tint-drop.png \
		png/youtube-logo-2.png \
		png/arrow-up.png \
		png/gamepad-console.png \
		png/arrowhead-pointing-to-the-right.png \
		png/sort-by-order.png \
		png/qr-code.png \
		png/increase-size-option.png \
		png/exchange-arrows.png \
		png/resize-option.png \
		png/caret-down.png \
		png/check-mark.png \
		png/fluffy-cloud-silhouette.png \
		png/medical-kit.png \
		png/exclamation.png \
		png/double-angle-pointing-to-right.png \
		png/instagram-symbol.png \
		png/yen-symbol.png \
		png/copy-document.png \
		png/apple-logo.png \
		png/square-shape-shadow.png \
		png/android-character-symbol.png \
		png/reorder-option.png \
		png/stack-exchange-symbol.png \
		png/circle-with-an-arrow-pointing-to-left.png \
		png/delivery-truck-silhouette.png \
		png/minus-button.png \
		png/question-sign.png \
		png/filter-tool-black-shape.png \
		png/left-indentation-option.png \
		png/hand-pointing-to-left-direction.png \
		png/u-shaped-thick-magnet.png \
		png/user-shape.png \
		png/magic-wand.png \
		png/bitbucket-sign.png \
		png/list-with-dots.png \
		png/tag-black-shape.png \
		png/thumbs-down-silhouette.png \
		png/long-arrow-pointing-to-left.png \
		png/cocktail-glass.png \
		png/left-arrow-1.png \
		png/magnifying-glass.png \
		png/cloud-storage-uploading-option.png \
		png/time.png \
		png/external-link-symbol.png \
		png/share-symbol.png \
		png/puzzle-piece-silhouette.png \
		png/paper-clip-outline.png \
		png/thin-arrowheads-pointing-down.png \
		png/bookmark-black-shape.png \
		png/computer-tablet.png \
		png/google-plus-symbol.png \
		png/chevron-sign-left.png \
		png/long-arrow-pointing-to-the-right.png \
		png/pinterest-logo.png \
		png/wheelchair.png \
		png/rss-symbol.png \
		png/rewind-button.png \
		png/sitemap.png \
		png/skype-logo.png \
		png/blank-file.png \
		png/volume-off.png \
		png/refresh-page-option.png \
		png/gittip-website-logo.png \
		png/table-grid.png \
		png/collapse-window-option.png \
		png/microphone-off.png \
		png/linux-logo.png \
		png/play-video-button.png \
		png/download-to-storage-drive.png \
		png/cloud-storage-download.png \
		png/font-symbol-of-letter-a.png \
		png/fullscreen-symbol.png \
		png/minus-symbol.png \
		png/github-logo.png \
		png/musical-bell-outline.png \
		png/mobile-phone.png \
		png/listing-option.png \
		png/chevron-up.png \
		png/twitter-sign.png \
		png/dropbox-logo.png \
		png/double-sided-eraser.png \
		png/bitcoin-logo.png \
		png/align-to-left.png \
		png/certificate-shape.png \
		png/rss-feed-button.png \
		png/user-md-symbol.png \
		png/map-marker.png \
		png/check-sign-in-a-rounded-black-square.png \
		png/bold-text-option.png \
		png/man.png \
		png/hostpital-building.png \
		png/checked-symbol.png \
		png/envelope.png \
		png/group-profile-users.png \
		png/exclamation-sign.png \
		png/strikethrough.png \
		png/cross-mark-on-a-black-circle-background.png \
		png/building-front.png \
		png/code-fork-symbol.png \
		png/arrow-pointing-right-in-a-circle.png \
		png/angle-pointing-to-left.png \
		png/add-square-button.png \
		png/inbox.png \
		png/check-box-empty.png \
		png/lightning-bolt-shadow.png \
		png/dribbble-logo.png \
		png/terminal.png \
		png/chevron-pointing-to-the-left.png \
		png/up-chevron-button.png \
		png/align-justify.png \
		png/picture.png \
		png/screenshot.png \
		png/arrow-up-on-a-black-circle-background.png \
		png/arrow-angle-pointing-down.png \
		png/twitter-black-shape.png \
		png/hard-drive.png \
		png/suitcase-with-white-details.png \
		png/fork-and-knife-silhouette.png \
		png/bull-horn-announcer.png \
		png/music-headphones.png \
		png/book.png \
		png/plus-black-symbol.png \
		png/eject-symbol.png \
		png/center-text-alignment.png \
		png/sort-up.png \
		png/up-arrow.png \
		png/earth-globe.png \
		png/ticket.png \
		png/text-width.png \
		png/umbrella-black-silhouette.png \
		png/upload.png \
		png/flickr-website-logo-silhouette.png \
		png/text-file.png \
		png/text-height-adjustment.png \
		png/briefcase.png \
		png/archive-black-box.png \
		png/keyboard.png \
		png/anchor-shape.png \
		png/comments.png \
		png/star-1.png \
		png/minus-sign-on-a-square-outline.png \
		png/two-columns-layout.png \
		png/barcode.png \
		png/pencil.png \
		png/cut.png \
		png/share-post-symbol.png \
		png/reply-arrow.png \
		png/bullseye.png \
		png/crop-symbol.png \
		png/level-up.png \
		png/angle-arrow-pointing-to-right.png \
		png/numbered-list.png \
		png/padlock.png \
		png/eye-open.png \
		png/pinterest-sign.png \
		png/shield.png \
		png/padlock-unlock.png \
		png/align-to-right.png \
		png/comment-white-oval-bubble.png \
		png/credit-card.png \
		png/eye-with-a-diagonal-line-interface-symbol-for-invisibility.png \
		png/plant-leaf-with-white-details.png \
		png/folder-white-shape.png \
		png/open-laptop-computer.png \
		png/save-file-option.png \
		png/linkedin-sign.png \
		png/calendar-with-spring-binder-and-date-blocks.png \
		png/gift-box.png \
		png/fighter-jet-silhouette.png \
		png/youtube-logo-1.png \
		png/maxcdn-website-logo.png \
		png/frown.png \
		png/down-arrow.png \
		png/linkedin-letters.png \
		png/star-half-empty.png \
		png/file.png \
		png/half-star-shape.png \
		png/settings.png \
		png/external-link-square-with-an-arrow-in-right-diagonal.png \
		png/foursquare-button.png \
		png/quote-left.png \
		png/github-sign.png \
		png/comment-black-oval-bubble-shape.png \
		png/information-button.png \
		png/long-arrow-pointing-up.png \
		png/tumblr-logo-1.png \
		png/film-strip-with-two-photograms.png \
		png/telephone-handle-silhouette.png \
		png/thumbs-up-hand-symbol.png \
		png/superscript-text-formatting.png \
		png/double-strikethrough-option.png \
		png/reduced-volume.png \
		png/music-note-black-symbol.png \
		png/xing-logotype.png \
		png/vintage-key-outline.png \
		png/heart-shape-outline.png \
		png/sun.png \
		png/white-flag-symbol.png \
		png/tumblr-logo.png \
		png/minus-sign-inside-a-black-rounded-square-shape.png \
		png/tasks-list.png \
		png/ban-circle-symbol.png
	/home/tyler/Qt/5.8/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

qrc_mapviewer.cpp: mapviewer.qrc \
		../../../Qt/5.8/gcc_64/bin/rcc \
		mapviewer/helper.js \
		mapviewer/MapViewer.qml \
		mapviewer/forms/LocaleForm.ui.qml \
		mapviewer/forms/RouteCoordinate.qml \
		mapviewer/forms/ReverseGeocode.qml \
		mapviewer/forms/RouteAddress.qml \
		mapviewer/forms/RouteList.qml \
		mapviewer/forms/GeocodeForm.ui.qml \
		mapviewer/forms/ReverseGeocodeForm.ui.qml \
		mapviewer/forms/Geocode.qml \
		mapviewer/forms/Message.qml \
		mapviewer/forms/RouteCoordinateForm.ui.qml \
		mapviewer/forms/RouteAddressForm.ui.qml \
		mapviewer/forms/RouteListHeader.qml \
		mapviewer/forms/MessageForm.ui.qml \
		mapviewer/forms/RouteListDelegate.qml \
		mapviewer/forms/Locale.qml \
		mapviewer/resources/icon.png \
		mapviewer/resources/scale_end.png \
		mapviewer/resources/scale.png \
		mapviewer/resources/marker.png \
		mapviewer/menus/MainMenu.qml \
		mapviewer/menus/MarkerPopupMenu.qml \
		mapviewer/menus/MapPopupMenu.qml \
		mapviewer/menus/ItemPopupMenu.qml \
		mapviewer/map/MapComponent.qml \
		mapviewer/map/ImageItem.qml \
		mapviewer/map/MiniMap.qml \
		mapviewer/map/RectangleItem.qml \
		mapviewer/map/Marker.qml \
		mapviewer/map/PolylineItem.qml \
		mapviewer/map/CircleItem.qml \
		mapviewer/map/PolygonItem.qml \
		mapviewer/doc/images/mapviewer.png \
		mapviewer/doc/src/mapviewer.qdoc
	/home/tyler/Qt/5.8/gcc_64/bin/rcc -name mapviewer mapviewer.qrc -o qrc_mapviewer.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.8/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_cvcontroller.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_cvcontroller.cpp
moc_cvcontroller.cpp: ../../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../OpenCV/modules/core/include/opencv2/core/core.hpp \
		../../../OpenCV/modules/core/include/opencv2/core.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvdef.h \
		../../../OpenCV/modules/core/include/opencv2/core/hal/interface.h \
		../../../OpenCV/modules/core/include/opencv2/core/version.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/base.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvstd.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/ptr.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/neon_utils.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/traits.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/matx.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/saturate.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/fast_math.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/types.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/mat.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/bufferpool.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/mat.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/persistence.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/operations.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvstd.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/utility.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/core_c.h \
		../../../OpenCV/modules/core/include/opencv2/core/types_c.h \
		../../../OpenCV/modules/core/include/opencv2/core/optim.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/ovx.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui/highgui.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui/highgui_c.h \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc/imgproc_c.h \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc/types_c.h \
		cvcontroller.h \
		moc_predefs.h \
		../../../Qt/5.8/gcc_64/bin/moc
	/home/tyler/Qt/5.8/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/tyler/Qt/5.8/gcc_64/mkspecs/linux-g++ -I/home/tyler/NEW_UAV/UAS/front -I/home/tyler/OpenCV/modules/core/include -I/home/tyler/OpenCV/modules/highgui/include -I/home/tyler/OpenCV/modules/objdetect/include -I/home/tyler/OpenCV/modules/imgproc/include -I/home/tyler/Qt/5.8/gcc_64/include -I/home/tyler/Qt/5.8/gcc_64/include/QtQuickControls2 -I/home/tyler/Qt/5.8/gcc_64/include/QtLocation -I/home/tyler/Qt/5.8/gcc_64/include/QtQuick -I/home/tyler/Qt/5.8/gcc_64/include/QtMultimedia -I/home/tyler/Qt/5.8/gcc_64/include/QtGui -I/home/tyler/Qt/5.8/gcc_64/include/QtQml -I/home/tyler/Qt/5.8/gcc_64/include/QtNetwork -I/home/tyler/Qt/5.8/gcc_64/include/QtPositioning -I/home/tyler/Qt/5.8/gcc_64/include/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include cvcontroller.h -o moc_cvcontroller.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Qt/5.8/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.8/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.8/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/5.8/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.8/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.8/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.8/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.8/gcc_64/include/QtQuick/QQuickView \
		../../../Qt/5.8/gcc_64/include/QtQuick/qquickview.h \
		../../../Qt/5.8/gcc_64/include/QtQuick/qquickwindow.h \
		../../../Qt/5.8/gcc_64/include/QtQuick/qtquickglobal.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qtqmlglobal.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qtqml-config.h \
		../../../Qt/5.8/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../../Qt/5.8/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../../Qt/5.8/gcc_64/include/QtQuick/qtquick-config.h \
		../../../Qt/5.8/gcc_64/include/QtQuick/qsgrendererinterface.h \
		../../../Qt/5.8/gcc_64/include/QtQuick/qsgnode.h \
		../../../Qt/5.8/gcc_64/include/QtQuick/qsggeometry.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qopengl.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qt_windows.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qopengles2ext.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qopenglext.h \
		../../../Qt/5.8/gcc_64/include/QtCore/QRectF \
		../../../Qt/5.8/gcc_64/include/QtGui/QMatrix4x4 \
		../../../Qt/5.8/gcc_64/include/QtGui/qmatrix4x4.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qvector3d.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qvector4d.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qquaternion.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qgenericmatrix.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qwindow.h \
		../../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../../Qt/5.8/gcc_64/include/QtCore/QEvent \
		../../../Qt/5.8/gcc_64/include/QtCore/QMargins \
		../../../Qt/5.8/gcc_64/include/QtCore/QRect \
		../../../Qt/5.8/gcc_64/include/QtGui/qsurface.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qsurfaceformat.h \
		../../../Qt/5.8/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qqml.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmlprivate.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmlparserstatus.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmllist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmetaobject.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmldebug.h \
		../../../Qt/5.8/gcc_64/include/QtCore/QDir \
		../../../Qt/5.8/gcc_64/include/QtCore/qdir.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qfileinfo.h \
		../../../Qt/5.8/gcc_64/include/QtQml/QQmlEngine \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmlengine.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qjsengine.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qjsvalue.h \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmlerror.h \
		../../../Qt/5.8/gcc_64/include/QtGui/QGuiApplication \
		../../../Qt/5.8/gcc_64/include/QtQml/QQmlApplicationEngine \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmlapplicationengine.h \
		../../../Qt/5.8/gcc_64/include/QtQml/QQmlContext \
		../../../Qt/5.8/gcc_64/include/QtQml/qqmlcontext.h \
		../../../Qt/5.8/gcc_64/include/QtGui/QScreen \
		../../../Qt/5.8/gcc_64/include/QtGui/qscreen.h \
		../../../Qt/5.8/gcc_64/include/QtCore/QList \
		../../../Qt/5.8/gcc_64/include/QtCore/QSize \
		../../../Qt/5.8/gcc_64/include/QtCore/QSizeF \
		../../../Qt/5.8/gcc_64/include/QtGui/QTransform \
		../../../Qt/5.8/gcc_64/include/QtCore/QSettings \
		../../../Qt/5.8/gcc_64/include/QtCore/qsettings.h \
		../../../Qt/5.8/gcc_64/include/QtQuickControls2/QQuickStyle \
		../../../Qt/5.8/gcc_64/include/QtQuickControls2/qquickstyle.h \
		../../../Qt/5.8/gcc_64/include/QtQuickControls2/qtquickcontrols2global.h \
		../../../Qt/5.8/gcc_64/include/QtGui/QFontDatabase \
		../../../Qt/5.8/gcc_64/include/QtGui/qfontdatabase.h \
		../../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../../Qt/5.8/gcc_64/include/QtCore/QTextStream \
		cvcontroller.h \
		../../../OpenCV/modules/core/include/opencv2/core/core.hpp \
		../../../OpenCV/modules/core/include/opencv2/core.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvdef.h \
		../../../OpenCV/modules/core/include/opencv2/core/hal/interface.h \
		../../../OpenCV/modules/core/include/opencv2/core/version.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/base.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvstd.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/ptr.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/neon_utils.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/traits.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/matx.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/saturate.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/fast_math.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/types.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/mat.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/bufferpool.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/mat.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/persistence.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/operations.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvstd.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/utility.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/core_c.h \
		../../../OpenCV/modules/core/include/opencv2/core/types_c.h \
		../../../OpenCV/modules/core/include/opencv2/core/optim.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/ovx.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui/highgui.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui/highgui_c.h \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc/imgproc_c.h \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc/types_c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

cvcontroller.o: cvcontroller.cpp cvcontroller.h \
		../../../Qt/5.8/gcc_64/include/QtCore/QObject \
		../../../Qt/5.8/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtypetraits.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qobject_impl.h \
		../../../OpenCV/modules/core/include/opencv2/core/core.hpp \
		../../../OpenCV/modules/core/include/opencv2/core.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvdef.h \
		../../../OpenCV/modules/core/include/opencv2/core/hal/interface.h \
		../../../OpenCV/modules/core/include/opencv2/core/version.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/base.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvstd.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/ptr.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/neon_utils.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/traits.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/matx.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/saturate.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/fast_math.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/types.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/mat.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/bufferpool.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/mat.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/persistence.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/operations.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/cvstd.inl.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/utility.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/core_c.h \
		../../../OpenCV/modules/core/include/opencv2/core/types_c.h \
		../../../OpenCV/modules/core/include/opencv2/core/optim.hpp \
		../../../OpenCV/modules/core/include/opencv2/core/ovx.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui/highgui.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui.hpp \
		../../../OpenCV/modules/highgui/include/opencv2/highgui/highgui_c.h \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc/imgproc_c.h \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc/types_c.h \
		../../../Qt/5.8/gcc_64/include/QtCore/QDebug \
		../../../Qt/5.8/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.8/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc/imgproc.hpp \
		../../../OpenCV/modules/imgproc/include/opencv2/imgproc.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cvcontroller.o cvcontroller.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

qrc_mapviewer.o: qrc_mapviewer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mapviewer.o qrc_mapviewer.cpp

moc_cvcontroller.o: moc_cvcontroller.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cvcontroller.o moc_cvcontroller.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/UAS_GS_Client/bin || mkdir -p $(INSTALL_ROOT)/opt/UAS_GS_Client/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/UAS_GS_Client/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/UAS_GS_Client/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/UAS_GS_Client/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

